DROP VIEW IF EXISTS "RaceTeamShipmentView" CASCADE;
DROP VIEW IF EXISTS "upcomingcriticalshipments2024" CASCADE;
DROP VIEW IF EXISTS "upcomingcriticalshipments" CASCADE;
DROP VIEW IF EXISTS "OverweightKits" CASCADE;

DROP TABLE IF EXISTS "KitContents" CASCADE;
DROP TABLE IF EXISTS "Kit" CASCADE;
DROP TABLE IF EXISTS "ContainerContents" CASCADE;
DROP TABLE IF EXISTS "Container" CASCADE;
DROP TABLE IF EXISTS "Shipment" CASCADE;
DROP TABLE IF EXISTS "RaceCrew_Member" CASCADE;
DROP TABLE IF EXISTS "TeamKit_Manager" CASCADE;
DROP TABLE IF EXISTS "Person" CASCADE;
DROP TABLE IF EXISTS "Team" CASCADE;
DROP TABLE IF EXISTS "Race_Event" CASCADE;
DROP TABLE IF EXISTS "Race_Event_Organizer" CASCADE;
