Table Race_Event {
  RaceID int [pk, not null, note: 'The current race'] 
  Location Text [note: 'The location of the race']
  Date dateTime [note: 'The time of the race']

  note: 'This table contains general information about the race'
}


Table Team_Table {
  TeamID int [pk, not null]
  RaceID int 
  TeamName text

  Note: 'Contains general team information'
}

Table Shipment {
  ShipmentID int [pk, not null]
  RaceID int
  CurrentLocation Text
  Destination Text 
  Method text [note: 'Ship, plane, truck, submarine, etc.']

  Note: 'The shipments contain all the containers'
}

Table Container {
  ConID int [pk, not null]
  ShipmentID int
  CriticalContainer boolean

  Note: 'Container can contain kits or f1 equipment'
}

Table Container_contains_TeamKits {
  ConID int
  KitID int
}

Table Container_contains_RaceKits {
  ConID int
  KitID int
}

Table Race_Kit {
  KitID int [pk, not null]

  Note: 'Contains f1 equipment'
}

Table Team_Kit {
  KitID int
  TeamID int

  Note: 'Contains individual team equipment'
}


Ref: Race_Event.RaceID < Team_Table.RaceID
Ref: Container.ConID < Container_contains_TeamKits.ConID
Ref: Container_contains_TeamKits.KitID - Team_Kit.KitID
Ref: Shipment.ShipmentID < Container.ShipmentID
Ref: Race_Event.RaceID < Shipment.RaceID
Ref: Team_Table.TeamID < Team_Kit.TeamID
Ref: Container.ConID < Container_contains_RaceKits.ConID
Ref: Container_contains_RaceKits.KitID < Race_Kit.KitID
